### ISSUE TITLE
Broken parser, does not match RFC, gives incorrect result

### ISSUE THREAD

**Issue by ioquatix** [brandur/http_accept#1]
This library is broken and does not conform to [RFC7231](https://tools.ietf.org/html/rfc7231#section-5.3.2)

``` ruby
HTTPAccept::Parser.new("foo/bar;q=1;bob=\"do,le\"").run                                                                                   
=> [#<HTTPAccept::MediaType:0x007f80d1328760 @format="foo/bar", @params={"q"=>"1", "bob"=>"do"}>,
 #<HTTPAccept::MediaType:0x007f80d13283f0 @format="le\"", @params={}>]
```

**Comment by brandur** [comment]
Thanks for reporting! Indeed this is a problem.

I spent a few minutes on this one, but unfortunately, my naive regex approach to parsing is poorly suited for correct adherence to the spec here. I think I'd need to refactor the library a little bit to produce a more legitimate attempt, which would take some time.

I'd also be happy to recommend a different library that does the job better if there is one out there. @ioquatix Did you find any that worked well for you?

**Comment by ioquatix** [comment]
@brandur I ended up making one :)

https://github.com/ioquatix/http-accept

**Comment by brandur** [comment]
@ioquatix Hah, well done!

**Comment by ioquatix** [comment]
Thanks. I think it's important that things like this are parsed correctly because it could lead to buggy behaviour and at worst security problems.
